### ISSUE TITLE
runtime arguments causing error

### ISSUE THREAD

**Issue by binnympaul** [ActivitySim/populationsim#102]
Following call results in error: `python run_populationsim.py --config configs`

Traceback (most recent call last):
  File "run_populationsim.py", line 63, in <module>
    pipeline.run(models=steps, resume_after=resume_after)
  File "C:\Users\binny.paul\Documents\Anaconda3\lib\site-packages\activitysim\core\pipeline.py", line 594, in run
    run_model(model)
  File "C:\Users\binny.paul\Documents\Anaconda3\lib\site-packages\activitysim\core\pipeline.py", line 471, in run_model
    orca.run([step_name])
  File "C:\Users\binny.paul\Documents\Anaconda3\lib\site-packages\activitysim\core\orca.py", line 2034, in run
    step()
  File "C:\Users\binny.paul\Documents\Anaconda3\lib\site-packages\activitysim\core\orca.py", line 843, in __call__
    return self._func(**kwargs)
  File "C:\Users\binny.paul\Documents\Anaconda3\lib\site-packages\populationsim\steps\setup_data_structures.py", line 317, in setup_data_structures
    control_spec = read_control_spec(setting('control_file_name', 'controls.csv'), configs_dir)
  File "C:\Users\binny.paul\Documents\Anaconda3\lib\site-packages\populationsim\steps\setup_data_structures.py", line 29, in read_control_spec
    data_file_path = os.path.join(configs_dir, data_filename)
  File "C:\Users\binny.paul\Documents\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
**TypeError: expected str, bytes or os.PathLike object, not list**

**Comment by binnympaul** [comment]
for now, just have default folder names - "data", "config", "output" and do not pass the folder names as arguments
