### ISSUE TITLE
Fail to integerize seed weights

### ISSUE THREAD

**Issue by gregmacfarlane** [ActivitySim/populationsim#107]
After moving beyond #104 and preparing our seed data in a better way, we now have an issue with integerizing the seed weights. Here's the stack trace:

```
INFO - integerize_final_seed_weights seed id 49003
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Oct 11 2019

command line - cbc -solve -quit (default strategy 1)
Presolve 31 (-6) rows, 335 (-7) columns and 3583 (-6) elements
0  Obj -0 Primal inf 393.88521 (16)
31  Obj -5027.9043 Primal inf 1.0552473 (3)
32  Obj -5027.9043
Optimal - objective value -5027.9043
After Postsolve, objective -5027.9043, infeasibilities - dual 0 (0), primal 0 (0)
Optimal objective -5027.904278 - 32 iterations time 0.002, Presolve 0.00
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00
Traceback (most recent call last):
  File "run_populationsim.py", line 63, in <module>
    pipeline.run(models=steps, resume_after=resume_after)
  File "/Users/gregmacfarlane/opt/anaconda3/envs/popsim/lib/python3.7/site-packages/activitysim/core/pipeline.py", line 594, in run
    run_model(model)
  File "/Users/gregmacfarlane/opt/anaconda3/envs/popsim/lib/python3.7/site-packages/activitysim/core/pipeline.py", line 471, in run_model
    orca.run([step_name])
  File "/Users/gregmacfarlane/opt/anaconda3/envs/popsim/lib/python3.7/site-packages/activitysim/core/orca.py", line 2034, in run
    step()
  File "/Users/gregmacfarlane/opt/anaconda3/envs/popsim/lib/python3.7/site-packages/activitysim/core/orca.py", line 843, in __call__
    return self._func(**kwargs)
  File "/Users/gregmacfarlane/opt/anaconda3/envs/popsim/lib/python3.7/site-packages/populationsim/steps/integerize_final_seed_weights.py", line 83, in integerize_final_seed_weights
    total_hh_control_col=total_hh_control_col
  File "/Users/gregmacfarlane/opt/anaconda3/envs/popsim/lib/python3.7/site-packages/populationsim/integerizer.py", line 308, in do_integerizing
    status = integerizer.integerize()
  File "/Users/gregmacfarlane/opt/anaconda3/envs/popsim/lib/python3.7/site-packages/populationsim/integerizer.py", line 187, in integerize
    smart_round(int_weights, resid_weights, self.total_hh_control_value)
  File "/Users/gregmacfarlane/opt/anaconda3/envs/popsim/lib/python3.7/site-packages/populationsim/integerizer.py", line 38, in smart_round
    assert target_sum == int(target_sum)
```

My guess is that this is an issue with data typing or configuring the weight field appropriately. We are using the basic `WGTP` field from the ACS PUMS record, and the person file has both the `WGTP` and `PWGTP` fields appended. We filtered households out that had `WGTP <= 0`, but are unsure if something else needs to happen. 

The repository is [here](https://github.com/byu-transpolab/populationsim_wfrc). We needed to remove the processed seed data from the repo for GitHub's limits (eventually) but the seed files are [here](https://byu.box.com/s/41g9afy6y27pb8i9mrlgoo6xfkq7bad9)

**Comment by bettinardi** [comment]
Poking around - I don't think this is the issue, but I would call out that I think these hhs need to be integers (maybe they don't, not 100% sure) - https://github.com/byu-transpolab/populationsim_wfrc/blob/master/data/control_totals_taz.csv

**Comment by bettinardi** [comment]
I don't have credentials to look at the seed, but I was going to see if the seed had any weird values for the weight field next

**Comment by bettinardi** [comment]
Actually this looks like it is looking at the household control, so maybe it does need to be an integer, like I suggest above...

packages/populationsim/integerizer.py", line 187, in integerize
    smart_round(int_weights, resid_weights, self.total_hh_control_value)

**Comment by gregmacfarlane** [comment]
Sorry, the link should now be shared with all. 

It's curious that there is a step to "integerize" the weights if they must be integers to begin with, right? What is it trying to round to?

**Comment by bettinardi** [comment]
To be clear - my suggestion is just a guess.
But I wasn't suggesting that the weights have to be integers going in.  I was saying the household controls need to be integers.  I think it integerizes all the seed weights so that they equal the control... maybe.  To make it clear - these are guesses from a user, not a developer.

**Comment by gregmacfarlane** [comment]
That was the issue.

**Comment by binnympaul** [comment]
Yes, PopulationSim performs better with integer controls (see #64 ). Non-integer controls can lead to failure of some assertion checks (I believe the differences are usually in decimals). Even if PopulationSim runs successfully with non-integer controls, the control match is much worse. Perhaps, we should add a section on data cleaning for PopulationSim.
