### ISSUE TITLE
ValueError: Grouper for <something> not 1-dimensional

### ISSUE THREAD

**Issue by marcomassano** [ActivitySim/populationsim#126]
When launching 'run_populationsim.py' it gives me the following error:
```
Traceback (most recent call last):
  File "run_populationsim.py", line 63, in <module>
    pipeline.run(models=steps, resume_after=resume_after)
  File "/home/aziz/anaconda3/envs/popsim/lib/python3.7/site-packages/activitysim/core/pipeline.py", line 594, in run
    run_model(model)
  File "/home/aziz/anaconda3/envs/popsim/lib/python3.7/site-packages/activitysim/core/pipeline.py", line 471, in run_model
    orca.run([step_name])
  File "/home/aziz/anaconda3/envs/popsim/lib/python3.7/site-packages/activitysim/core/orca.py", line 2034, in run
    step()
  File "/home/aziz/anaconda3/envs/popsim/lib/python3.7/site-packages/activitysim/core/orca.py", line 843, in __call__
    return self._func(**kwargs)
  File "/home/aziz/anaconda3/envs/popsim/lib/python3.7/site-packages/populationsim/steps/setup_data_structures.py", line 332, in setup_data_structures
    incidence_table = add_geography_columns(incidence_table, households_df, crosswalk_df)
  File "/home/aziz/anaconda3/envs/popsim/lib/python3.7/site-packages/populationsim/steps/setup_data_structures.py", line 117, in add_geography_columns
    .groupby(seed_geography, as_index=True).min()[meta_geography]
  File "/home/aziz/anaconda3/envs/popsim/lib/python3.7/site-packages/pandas/core/frame.py", line 5810, in groupby
    observed=observed,
  File "/home/aziz/anaconda3/envs/popsim/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 410, in __init__
    mutated=self.mutated,
  File "/home/aziz/anaconda3/envs/popsim/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 627, in get_grouper
    if not isinstance(gpr, Grouping)
  File "/home/aziz/anaconda3/envs/popsim/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 345, in __init__
    raise ValueError(f"Grouper for '{t}' not 1-dimensional")
ValueError: Grouper for 'COM' not 1-dimensional
```

'COM' is my seed geography.
I've got the following geographies: [COM,NSEZ]

I add a zip file with all my input data and settings that had produced the error.

Does somebody have a solution for my problem?
[my_exercise.zip](https://github.com/ActivitySim/populationsim/files/5208536/my_exercise.zip)

**Comment by binnympaul** [comment]
Hi @marcomassano, were you able to resolve this error?

I think the meta geography is missing. Can you try adding a meta geography. If you do not have one, you can create a dummy meta geography representing the whole region. For example, your crosswalk would looks something line this:

NSEZ | COM | Region
-- | -- | --
1 | 272 | 1
2 | 272 | 1
3 | 272 | 1
4 | 272 | 1
6 | 272 | 1
7 | 272 | 1
8 | 272 | 1
9 | 272 | 1

where Region will be one always. The geographies setting will be
geographies: [Region,COM,NSEZ]

**Comment by bettinardi** [comment]
@binnympaul - thanks for this answer from 3 years ago Binny
It's helping us again (the benefits of using a git forum and not email).  We will add the region geography - do we also need a region control (I'm trying to run without a PUMA level control).

**Comment by binnympaul** [comment]
Hi @bettinardi, glad to know that this was helpful after three years! It should work without regional controls. It would skip the meta-factoring step and go straight to final seed balancing.

**Comment by binnympaul** [comment]
@bettinardi: if you are using the latest version then not having meta controls should not cause any errors. The error is happening in the initial seed balancing step (before meta factoring) itself so it seems like a different issue.

**Comment by bettinardi** [comment]
Does the phrase "no objects to concatenate" give you any thoughts as to what part of the seed or crosswalk might still be off - we're still not able to figure out what is missing.

**Comment by bettinardi** [comment]
Never mind - on that error.  We had an error in our crosswalk, where a save in excel wiped out the block and block group numbers (turned them into scientific notation).  We are not passed that error and stuck on a "did not converge" error in seed balancing.

**Comment by bettinardi** [comment]
Still digging in, but it looks like that our control files were inconsistent with the crosswalk.  I'll update the thread as we resolve the issue.

**Comment by bettinardi** [comment]
The issues we were running into were all related to inconsistencies in the seed, crosswalk, and controls files.

**Comment by binnympaul** [comment]
Yes, 99% of the time the errors are related to data inconsistency issues.
