### ISSUE TITLE
Running Error: Lengths must match to compare on "integerize_final_seed_weights'"

### ISSUE THREAD

**Issue by kata26rakuda** [ActivitySim/populationsim#173]
Hi, I am facing the following error with the attached dataset.
Could someone kindly help me to solve this error?

---------------------------------
Running step 'meta_control_factoring'
INFO - mp_seed_balancing initial_seed_balancing : 389.047 seconds (6.5 minutes)
WARNING - meta_control_factoring: no meta targets so nothing to do
Time to execute step 'meta_control_factoring': 0.05 s
Total time to execute iteration 1 with iteration value None: 0.05 s
INFO - #run_model running step final_seed_balancing
Running step 'final_seed_balancing'
WARNING - no need for final_seed_balancing because no meta controls
Time to execute step 'final_seed_balancing': 0.06 s
Total time to execute iteration 1 with iteration value None: 0.06 s
INFO - #run_model running step integerize_final_seed_weights
Running step 'integerize_final_seed_weights'
WARNING - ValueError exception running integerize_final_seed_weights model: Lengths must match to compare
ERROR - mp_tasks - mp_seed_balancing - ValueError exception caught in mp_run_simulation: Lengths must match to compare
--------------------------------
Best regards,

[sample.zip](https://github.com/ActivitySim/populationsim/files/11158579/sample.zip)

**Comment by binnympaul** [comment]
I also haven't looked through all the files but as @bettinardi pointed out, TAZs cannot be set as the seed geography in this case. In PopulationSim, there can be only one meta-geography above the seed geography. Any geography can be set as the seed geography (need not be PUMA always), provided there is only one geography above it. So in this case, TRACT should be set as the seed geography. Please try setting TRACT as the seed.

**Comment by kata26rakuda** [comment]
@bettinardi @binnympaul Thank you so much for your suggestion. I modified the configuration setting.yaml to set TRACT as the seed geography as attached, and then it seems the current issue has been solved. However, I am still facing another error ("assert weights_df is not None") at sub_balancing.geography=TRACT model (populationsim/steps/sub_balancing.py,  line 236) as follows. Do you have any idea to solve this error?

-----------------------------------------

Running step 'sub_balancing'
WARNING - AssertionError exception running sub_balancing.geography=TRACT model:
ERROR - mp_tasks - mp_seed_balancing - AssertionError exception caught in mp_run_simulation:
ERROR -
---
Traceback (most recent call last):
  File "C:\Users\oc3490\anaconda3\envs\popsim\lib\site-packages\activitysim\core\mp_tasks.py", line 915, in mp_run_simulation
    run_simulation(queue, step_info, resume_after, shared_data_buffer)
  File "C:\Users\oc3490\anaconda3\envs\popsim\lib\site-packages\activitysim\core\mp_tasks.py", line 867, in run_simulation
    raise e
  File "C:\Users\oc3490\anaconda3\envs\popsim\lib\site-packages\activitysim\core\mp_tasks.py", line 864, in run_simulation
    pipeline.run_model(model)
  File "C:\Users\oc3490\anaconda3\envs\popsim\lib\site-packages\activitysim\core\pipeline.py", line 502, in run_model
    orca.run([step_name])
  File "C:\Users\oc3490\anaconda3\envs\popsim\lib\site-packages\orca\orca.py", line 2177, in run
    step()
  File "C:\Users\oc3490\anaconda3\envs\popsim\lib\site-packages\orca\orca.py", line 973, in __call__
    return self._func(**kwargs)
  File "C:\Users\oc3490\anaconda3\envs\popsim\lib\site-packages\populationsim\steps\sub_balancing.py", line 236, in sub_balancing
    assert weights_df is not None
AssertionError
---

[configs.zip](https://github.com/ActivitySim/populationsim/files/11166044/configs.zip)

**Comment by kata26rakuda** [comment]
Hello, is there any one to provide some ways to solve this issue to me?

**Comment by bettinardi** [comment]
I'm sorry that no one has been able to respond.  In general it seems like your attempts are outside of the way we were thinking Popsim would be used.   So I think Popsim is breaking because we didn't anticipate the configuration you are attempting.  To fix it, I think Binny or myself or someone familiar with PopSim would need to comb through your setup / approach and fully review and try to reconfigure the approach to get it working.  It's possible it's something simple, but it's hard to guess without more fully getting up to speed with what you are attempting (at least for myself - to be able to respond I would need to fully review and understand your set up).  So my only real suggestion (which is not very helpful), is to try and refer back to the instructions add attempt to test re-configuring your setup closer and closer to provided examples or instructions to get it to work and then back out from there, what is different in your approach that is breaking the tool - https://activitysim.github.io/populationsim/.

Were you able to get an example to run that you can refer back to?

**Comment by binnympaul** [comment]
I also suggest you review the examples in the repository and the instructions. Your error seems to be due to an inconsistent configuration of the settings file. Complete instructions on configuring the settings file are here: https://activitysim.github.io/populationsim/application_configuration.html#configuring-settings-file

As @bettinardi mentioned, it is not very easy to debug without looking at the setup. It seems like you have a sub-balancing step for your seed geography (TAZ) in the run_list. You cannot have a sub-balancing step for the seed geography. Try correcting that and see if it fixes the issue for you.

Reading through the entire wiki will be very helpful. There are links to additional resources including a training package here: https://activitysim.github.io/populationsim/docs.html#external-resources

**Comment by kata26rakuda** [comment]
@binnympaul @bettinardi Thank you so much for your reply. As @binnympaul pointed out, the sub-balancing setting seems to occur the error which I have encountered. After fixing this setting with non-seed geopraphy, the program is running well now. I appreciated your suggestion.

**Comment by bettinardi** [comment]
This looks resolved - hopefully I'm closing correctly
