### ISSUE TITLE
Repop Error

### ISSUE THREAD

**Issue by Jxr99int2013** [ActivitySim/populationsim#180]
I wonder if anyone here has seen the following "repop" message:

Traceback (most recent call last):
  File "run_populationsim.py", line 62, in <module>
    pipeline.run(models=steps, resume_after=resume_after)
  File "H:\Tools\ModelingTools\PopulationSim\Anaconda2\envs\popsim\lib\site-packages\activitysim\core\pipeline.py", line 565, in run
    open_pipeline(resume_after)
  File "H:\Tools\ModelingTools\PopulationSim\Anaconda2\envs\popsim\lib\site-packages\activitysim\core\pipeline.py", line 503, in open_pipeline
    load_checkpoint(resume_after)
  File "H:\Tools\ModelingTools\PopulationSim\Anaconda2\envs\popsim\lib\site-packages\activitysim\core\pipeline.py", line 417, in load_checkpoint
    _PIPELINE.prng.load_channels(cPickle.loads(_PIPELINE.last_checkpoint[PRNG_CHANNELS]))
KeyError: 'prng_channels'
Closing remaining open files:output\pipeline.h5...done
PopulationSim run complete!!
12:01:59.01
Press any key to continue . . .

**Comment by bettinardi** [comment]
I believe we found a way forward on this - correct Jin?
I'm going to close this for now - if it is still an issue, I imagine the improved examples and documentation on Re-pop that we are working to resolve should help issues like this.
