### ISSUE TITLE
Installation outdated and not functional

### ISSUE THREAD

**Issue by MSnPTV** [ActivitySim/populationsim#183]
The installation process as it is described on https://activitysim.github.io/populationsim/getting_started.html#installation does not lead to a functioning working environment. Any python run ends with the error message 

> Traceback (most recent call last):
>   File "D:\MSn\PopSim\example_calm\run_populationsim.py", line 39, in <module>
>     sys.exit(run(args))
>   File "D:\MSn\PopSimInstallTest\lib\site-packages\activitysim\cli\run.py", line 329, in run
>     info = np.__config__.get_info(cfg_key)
> AttributeError: module 'numpy.__config__' has no attribute 'get_info'

The installation process installs Python modules that are not compatible with each other. Although nothing has changed in the code for some time, this happens because the installation program is instructed to use the latest version of each package. And of course that has changed in recent years. And now not all modules are compatible.

**Comment by GregorSchroeder** [comment]
Seeing similar issue as well. If anyone has information on how to resolve please update. Otherwise will continue to investigate.

**Comment by brynpickering** [comment]
`conda install "numpy < 1.20"` _should_ do the trick. I have found that creating the initial conda environment with some more content than just python works well: `conda create -n popsim python=3.9 numpy<1.20 pandas<1.5 activitysim; conda activate popsim; pip install populationsim`
